### ISSUE TITLE
Exception when using the example mentioned in readme file.

### ISSUE THREAD

**Issue by ranveer5289** [qoda/python-wkhtmltopdf#5]
I copied the exampe mentioned in the readme file and now when  I try to run my python script I get the following error:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    wkhtmltopdf(url='http://google.com',output_file='~/out.pdf',)
  File "/usr/local/lib/python2.7/dist-packages/wkhtmltopdf-master-py2.7.egg/wkhtmltopdf/main.py", line 190, in wkhtmltopdf
    wkhp = WKhtmlToPdf(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wkhtmltopdf-master-py2.7.egg/wkhtmltopdf/main.py", line 131, in **init**
    raise Exception("Missing url and output file arguments")
Exception: Missing url and output file arguments 

Here is the code:

from wkhtmltopdf import wkhtmltopdf
wkhtmltopdf(url='http://google.com',output_file='~/out.pdf',)

Any idea what is wrong here. I also tried the other example(_Use from class_) but it also raised the same error.

**Comment by qoda** [comment]
No longer in development
